travis:
  secure:
    BINSTAR_TOKEN: oEgegelvobPLZVSdEsy0zbqU7s0ZXGvNQLnJgVdm1GpJI2cQAZng7PVpj6ocaFTWJq76q26CYacIu1E8j7F44wc9FeJVj4+cZZS2CfEIy+9Wcn+YChPIk8mdI2giJi7PF5/YDVmFluHxoWkhWbaQ3O2jnHuhuNIn0NwWMDnHRrFgPnO3YtGFum404zPFcsqQHz3MqZGD0o+xjrfp50hiRmY1cAX8Yp6U0EOOxu+DHBChtv0g15NmMaQaTZStZMTNWakU0LrNI7FTqLT3x9hl9WRvpFeQ0Q4NckW4kIj8N8dR1gayvVEzakeKT5cPgIxP5VpRzucC55i2W/c/51GiGfg+6UQStk8tkZDeA4TzocI5IvY5d+lx1hvol7yCy7nxubtGQyaWXx7LMMM1Ukl2wPvzd3nZuMtefWWpNyDT5CH2yLNnV6KgAWXz2qPMChe3+pkOK/vVOWI8GoqK1SnbBpsqYvVIreSg5ltXItOwvpgesdrNn3TVbZY1j3s10509p103AnlaYqD/UlTQDK848mS+YNcjUhd5V2TIYc5ngia0xCjquyPanwpDJ7pAABe+3eM/i0LAtvG0A8sYC5CtaOhgx1a+5VqJsRGG7yr8zRiFyrS6DIrVRvh10YgySLcZZ/aE7b7ZnE1KvSabFZ0o2ft6FC3jtE/FinrGCdVrgn0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
