travis:
  secure:
    BINSTAR_TOKEN: g1ZG3Kkp1XI3tVqVUNDuNSILhMpOarBv7pBEkCGYKukg/6KuWr6OXTxgsxOe2vOtOEPZgQXGJ1JkpsdiSoRsJE4bFK+0Jaxz/CEELSrWl8929M8ih2nrfpcR03Wdmj3NNpyJtC/s6zUd1wV9l+poprpR1PJBF1eFObdfl1M8mEYIfkTHiwxe+dPAOQf2wRcOtxaeneSpsm440FoJ75EJGUsx3JikZT+uxyHbQj0B56TZcJdauT6eyLQlLvDbFf3EBuEeXS3cUkI1QE8cjR1osXmgLBpXWAia9khuWeqmDbcZdxrfRTccESJzLQR0E/trPCRLNkLkYtRWP48VZFKwGm0tBmZFlj2EtUm8LBNliH9cx/O3F5+leWiZERvjxAVAHHiDylokiktimmRIfcpJd6xhFskOHW8xDTyba0RJACL33ClQRhGlY6u3Di+YGC0mkTrLeNWMcd2yv30INfL5cIOSNRLuidoj1z8rv5jEXvlxTvRNQKW/Liibhf856R4FeWCjws9BLXK5OcRP5NZz0kX8UgXAqE9tbv3QiU4oBmjOWxbl2UBhj32AgRzQ/aYRTLbG7BvKSF+Wjhz784NiLV3Nbt7+CcNkBNGkWL64nWfB7YUSRhm44d3RJHRWc0HvNJ4gXFs0B5zTlfZR0uFATTHEBA7C4xlrsAMeneZSJkM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
